"""Update school and base models

Revision ID: 001d4321649a
Revises: f49783259bfa
Create Date: 2024-10-19 22:12:43.366258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001d4321649a'
down_revision: Union[str, None] = 'f49783259bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fingerprints', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fingerprints', 'schools', ['school_id'], ['id'])
    op.add_column('revoked_tokens', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'revoked_tokens', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revoked_tokens', type_='foreignkey')
    op.drop_column('revoked_tokens', 'school_id')
    op.drop_constraint(None, 'fingerprints', type_='foreignkey')
    op.drop_column('fingerprints', 'school_id')
    # ### end Alembic commands ###
