"""Add school_type to School model

Revision ID: 42d002fa9ed7
Revises: 6971545d6681
Create Date: 2024-12-26 08:27:19.528396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d002fa9ed7'
down_revision: Union[str, None] = '6971545d6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('school_type', sa.String(length=50), nullable=True))
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('schools', 'school_type')
    # ### end Alembic commands ###
