"""Add website column to schools table

Revision ID: 63b0750f9f8b
Revises: 42d002fa9ed7
Create Date: 2024-12-26 14:30:44.687664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b0750f9f8b'
down_revision: Union[str, None] = '42d002fa9ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('website', sa.String(length=255), nullable=True))
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('schools', 'website')
    # ### end Alembic commands ###
