"""Add registration_number column to School model

Revision ID: 6971545d6681
Revises: 3b4596f88ad4
Create Date: 2024-12-26 08:20:08.319717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6971545d6681'
down_revision: Union[str, None] = '3b4596f88ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'schools', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='unique')
    op.drop_column('schools', 'registration_number')
    # ### end Alembic commands ###
