"""Fix attendance relationships

Revision ID: ff44bc094dc4
Revises: 63b0750f9f8b
Create Date: 2024-12-28 14:18:15.609194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff44bc094dc4'
down_revision: Union[str, None] = '63b0750f9f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('student_attendances', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher_attendances', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_attendances', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_attendances', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schools', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
